apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    version: v1         # Matches pods from your db-deployment
  ports:
    - protocol: TCP
      port: 3306        # Port exposed by the service
      targetPort: 3306  # Port on the container
  type: ClusterIP       # Default type - accessible only within the cluster
