apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: wp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wp-configmap
                optional: false
            - secretRef:
                name: wp-secret
                optional: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-configmap
  namespace: wp
  labels:
    app: wordpress
    env: prod
data:
  WORDPRESS_DB_HOST: db-service.db.svc.cluster.local
  WORDPRESS_DB_NAME: wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wp
type: Opaque
data:
  WORDPRESS_DB_USER: d29yZHByZXNz        # base64 for "wordpress"
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz    # base64 for "wordpress"
